[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Yunwen Tao", email = "ywtao@smu"}]
dynamic = ["version", "description"]
